### ISSUE TITLE
Cannot do "Bring Equestria In" focus cuz you have lvl 2 verdant accord

### ISSUE THREAD

**Issue by randomguyingithub** [rare-rit-y/madkirin#1]
mods about horse that at wars? nah uh
![hoi4_2405202255_cl9HT](https://github.com/rare-rit-y/madkirin/assets/13596387/7c9000a8-9d03-4694-8450-8382c31489b2)
![hoi4_2405202255_m3cGJ](https://github.com/rare-rit-y/madkirin/assets/13596387/48fcc010-9f39-4761-976e-4b07e54dd161)

**Comment by rare-rit-y** [comment]
WTF!!!!!!!!!!!!!!!!!
sorry about overlooking, fixed

**Comment by rare-rit-y** [comment]
thank you very much
