### ISSUE TITLE
Persimmon Smoke can't be hired

### ISSUE THREAD

**Issue by Corvid-Systems** [rare-rit-y/madkirin#2]
The focus BAC_COC_mil_navy "Beyond The Riverine Navy" moves the advisor KIC_navy_chief_1 "Persimmon Smoke" to your country. However, it doesn't give you the ability to *hire* that advisor, as the character file specifies they're only visible if you've completed focus KIR_republic_focus_BH_3B (which is, of course, from a different focus tree).

**Comment by rare-rit-y** [comment]
fixed by replacing with another kirin, thank you so much.
