### ISSUE TITLE
Air MIOs can't be used

### ISSUE THREAD

**Issue by Corvid-Systems** [rare-rit-y/madkirin#3]
The focus BAC_COC_mil_air "Flying Commonkirin" doesn't actually enable the two Military Industrial Organizations it's supposed to give you; the issue, as far as I can tell, is that it's setting the wrong country flags?

Namely, that it's setting the flags BAC_KIR_DM_aerospace_engineering_available and BAC_KIC_aerospace_engineer_available, but should be setting the flags KIR_DM_aerospace_engineering_available and KIC_aerospace_engineer_available.

**Comment by rare-rit-y** [comment]
what a shame, thanks for this report. I just fixed the code.

I recall trying to create clone concerns to have another trait, apparently I didn't reverted it...
